title: ETYLL JOY ZARCO
#logo: /assets/img/headshot_circle.png
logo: https://raw.githubusercontent.com/ejoytech/portfolio/main/profile.jpg
#description: text below image
show_downloads: true
theme: jekyll-theme-minimal
#theme: jekyll-theme-architect
