title: ETYLL JOY ZARCO
#logo: /assets/img/headshot_circle.png
#logo: https://raw.githubusercontent.com/ejoytech/portfolio/main/profile.jpg
logo: https://raw.githubusercontent.com/ejoytech/portfolio/main/download.jpg
#description: text below image
show_downloads: true
theme: jekyll-theme-minimal
#theme: jekyll-theme-architect



git add path/to/PDFCerts/Zarco_Etyll_Joy_Microsoft_AZ-104.pdf
git commit -m "Add certificate PDF"
git push origin main
