title: Shaw Talebi
#logo: /assets/img/headshot_circle.png
logo: https://github.com/ejoytech/portfolio/blob/main/profile.jpg
#description: text below image
show_downloads: true
theme: jekyll-theme-minimal
#theme: jekyll-theme-architect
